Algoritmo "6"

Var
   km, horas, ms, vm:real
   temp:real

Inicio
      escreva("informe o espaça pecorrido e quilometros:")
      leia(km)
      escreva ("informe o tempo gasto em horas:")
      leia (horas)
      vm <- km / horas
      escreva("velocidade media " ,vm:8:2)
      escreva("km/h")
       ms <- km / 3,6
       escreva(" a volocidade em ms é" , ms,"metros por segundo")
       vm <-434.400 / km
       escreva( " o tempo gasto de sao paulo para rio e de",vm)


Fimalgoritmo