Algoritmo "Media do aluno"

Var
  n1,n2,n3,n4,n5, media : real


Inicio
     escreval("informe a primeira nota: ")
      leia (n1)
      escreval ("informe a segunda nota : ")
       leia (n2)
       escreval ("informe a terceira nota: ")
       leia (n3)
       escreval ("informe a quarta nota: ")
       leia (n4)
       escreval ("informe a quinta nota:")
       leia (n5)
       media := (n1+n2+n3+n4+n5) / 5
       escreval ("a media final do aluno foi de :", media)
Fimalgoritmo